### ISSUE TITLE
We should not try to update config file when there are no changes

### ISSUE THREAD

**Issue by hphilm** [manjaro-kernels/kernel-action#10]
CI will fail when we try to update config file when there are no changes: https://github.com/manjaro-kernels/linux67/actions/runs/6925184916. Therefore we should add a check and only commit changes if there are some.

**Comment by oberon-manjaro** [comment]
fixed with https://github.com/manjaro-kernels/kernel-action/commit/e3afada2864eec058220982c2c94b5fe211ae3a3
