### ISSUE TITLE
[improve] remove folder structure of log tarball

### ISSUE THREAD

**Issue by hphilm** [manjaro-kernels/kernel-action#13]
Using some like this would remove the folder structure of that archive:

`tar --transform 's/.*\///g' -zcvf tarballName.tgz */*/*.info`

See also for other options to achieve the same: https://superuser.com/questions/272213/tar-files-without-directory-structure

### Benefit

You will see the log files in the root folder. No need to click thru a folder structure to get there.

**Comment by oberon-manjaro** [comment]
Tested and works as expected.
