### ISSUE TITLE
Installing packages after build may fail on DB updates

### ISSUE THREAD

**Issue by hphilm** [manjaro-kernels/kernel-action#2]
Using **github** actions might take longer to compile a Kernel. In this time of almost 1.5 hrs a lot can happen on the package server side. It is recommended to update the databases before installing packages with pacman using the `-U` flag.

**makepkg** uses following routine:

```
run_pacman() {
	local cmd cmdescape
	if [[ $1 = -@(T|Q)*([[:alpha:]]) ]]; then
		cmd=("$PACMAN_PATH" "$@")
	else
		cmd=("$PACMAN_PATH" "${PACMAN_OPTS[@]}" "$@")
		cmdescape="$(printf '%q ' "${cmd[@]}")"
		if (( ${#PACMAN_AUTH[@]} )); then
			if in_array '%c' "${PACMAN_AUTH[@]}"; then
				cmd=("${PACMAN_AUTH[@]/\%c/$cmdescape}")
			else
				cmd=("${PACMAN_AUTH[@]}" "${cmd[@]}")
			fi
		elif type -p sudo >/dev/null; then
			cmd=(sudo "${cmd[@]}")
		else
			cmd=(su root -c "$cmdescape")
		fi
		local lockfile="$(pacman-conf DBPath)/db.lck"
		while [[ -f $lockfile ]]; do
			local timer=0
			msg "$(gettext "Pacman is currently in use, please wait...")"
			while [[ -f $lockfile ]] && (( timer < 10 )); do
				(( ++timer ))
				sleep 3
			done
		done
	fi
	"${cmd[@]}"
}
```

A `"$PACMAN_PATH" "-Syy"` before `"${cmd[@]}"` should fix that.

**Comment by oberon-manjaro** [comment]
So you want to patch makepkg in pacman??

First of all I think it's a rare and quite unlikely case that one of the few kernel dependencies gets updated during exactly one build routine.

If we want to absolutely rule out the risk, we can:
- run chrootbuild for the kernel without the -n option, thus not install it after build
- publish kernel files
- invoke module.list build with chrootbuild -i to install local kernel packges

**Comment by hphilm** [comment]
Well, both ways would work. Your idea might install the kernel more than once. Editing one script with sed or so wouldn't  hurt.

**Comment by oberon-manjaro** [comment]
chrootbuild -i option will install kernel pkgs only once for a list build

**Comment by hphilm** [comment]
Well, I'm fine with any solution. Just saying ...
