### ISSUE TITLE
bumprel funcion of CI can't handle non-existing packages

### ISSUE THREAD

**Issue by hphilm** [manjaro-kernels/kernel-action#8]
The CI, when updating pkgrel it looks for the version in the repo. When the package doesn't exist, yet it creates an error. that's why the list doesn't include modules that don't yet build successfully.

We should work on a function to ignore non-existing packages and try to build them anyhow. This will show us exactly the errors as each RC kernel may add new functions or fixes.

This way we can create issues better and don't have to check locally for these errors.

**Comment by oberon-manjaro** [comment]
almost always the build issues are fixed in the module, not the kernel. for that reason I think a function like that is not helpful at all. the modules need to be fixed manually with pathces or updates anyway.

**Comment by hphilm** [comment]
Each RC changes the code and may fix or add new ones. Also the user who follow RCs can simply check the log which of those modules won't build and why. Then they can help to find patches ...

**Comment by hphilm** [comment]
possible fix:

```
--- orig	2023-04-25 03:40:29.982541162 +0700
+++ modified	2023-04-25 03:41:44.802566744 +0700
@@ -5,6 +5,7 @@
         sudo sed -i -e '/^#/d' modules.list
         sudo mkdir modules
         pushd modules
+        sudo pacman -Sy
         for m in $(cat ../modules.list); do
           if [[ "${{ inputs.realtime }}" == "true" ]]; then
             sudo git clone "https://mjr-build-server:${{ inputs.gitlab-pw }}@gitlab.manjaro.org/packages/community/realtime-kernels/${{ env.KERNEL }}-extramodules/$m.git"
@@ -16,7 +17,8 @@
             [[ $m == "spl_zfs" ]] && _m=zfs
             [[ $m == "virtualbox-modules" ]] && _m=virtualbox-host-modules
             cd $m
-            repover=$(sudo pacman -Syi ${{ env.KERNEL }}-$_m | grep Version | rev | cut -d' ' -f1 | rev)
+            repover=$(pacman -Si ${{ env.KERNEL }}-$_m | grep Version | rev | cut -d' ' -f1 | rev || TRUE)
+            [[ -z $repover ]] && continue
             _reporel=$(echo $repover | cut -d- -f2)
             _gitrel=$(grep "^pkgrel=" PKGBUILD | cut -d= -f2)
             if [[ "${{ inputs.bump-modules }}" == "git" ]]; then
```

This also removes the DB updates between modules.

**Comment by oberon-manjaro** [comment]
Fixed this properly now.
Pkgrel will not be bumped for non-existant packages and also no attemps to commit unchanged files to git.

**Comment by oberon-manjaro** [comment]
Works as expected:
https://github.com/manjaro-kernels/linux64/actions/runs/4980848092/jobs/8914283839#step:2:63550
```
Cloning into 'nvidia'...
error: package 'linux64-nvidia' was not found
nvidia doesn't exist yet in repo. Attempting initial build.
```
and https://github.com/manjaro-kernels/linux64/actions/runs/4980848092/jobs/8914283839#step:2:63550
